### PR TITLE
change from vercel to cloudflare

### PR DESCRIPTION
**Pull request by micoms**

### CODE REVIEW

**Comment by trollm8** [comment]
We do not support cloudflare, as it errors out. when we attempt to merge a pr with it.

**Comment by cupglassDEV** [comment]
CF only supports domain that already been inserted to PSL, like is-a.dev

Or just a plain tld with your literal domain inside (helloimstupid.dev, example.com, etc)

**Comment by trollm8** [comment]
We will try to get it on psl soon.

**Comment by cupglassDEV** [comment]
> We will try to get it on psl soon.

Thats great!

**Comment by CuteDog5695** [comment]
> We will try to get it on psl soon.

We would need a pretty good reason for PSL though

**Comment by cupglassDEV** [comment]
> > We will try to get it on psl soon.
> 
> We would need a pretty good reason for PSL though

gif

**Comment by EducatedSuddenBucket** [comment]
Hi dumb persons @trollm8 @CuteDog5695 @cupglassDEV , the person is trying to use cloudflare pages not cloudflare dns cloudflare pages doesn't have any specific requirements here is example test.e.is-not.cool which works and u can check that cname is cloudflare pages u can chek it's dns records at https://digger.tools/lookup/test.e.is-not.cool

**Comment by CuteDog5695** [comment]
I didn't even see it, I only saw cupglass and trollm8 talking about PSL, which I replied on that context.

@micoms Do you want this domain still?

**Comment by EducatedSuddenBucket** [comment]
> If you stupid enough to know wth is PSL, PSL stands for Public Suffix List. PSL is used when someone CAN register under that root domain (like is-a.dev, is-not.cool, is-truly-a.pro, etc). PSL is maintained by Mozilla (yeah, that controversial Firefox's creator) Actually (again), PSL is used by some countries like co.kr, net.id, or.id, and much more
@cupglassDEV I want to correct your sentence, it not "someone can register "it should be "everyone"  that is why it's called "public" suffix list. You  can request subdomains of any domain in the psl like william's domain like wdh.app

**Comment by CuteDog5695** [comment]
> You can request subdomains of any domain in the psl like william's domain like wdh.app

I'd like to make a objection for that. For `wdh.app` I think it was for his own projects, while our domain is a subdomain service. We also need to have a pretty valid reason for PSL. Could be wrong though, but anyways.

**Comment by cupglassDEV** [comment]
@EducatedSuddenBucket 

> > If you stupid enough to know wth is PSL, PSL stands for Public Suffix List. PSL is used when someone CAN register under that root domain (like is-a.dev, is-not.cool, is-truly-a.pro, etc). PSL is maintained by Mozilla (yeah, that controversial Firefox's creator) Actually (again), PSL is used by some countries like co.kr, net.id, or.id, and much more
> 
> @cupglassDEV I want to correct your sentence, it not "someone can register "it should be "everyone" that is why it's called "public" suffix list. You can request subdomains of any domain in the psl like william's domain like wdh.app

Alright alright, im reading the fricking docs so... https://publicsuffix.org
image

**Comment by trollm8** [comment]
@EducatedSuddenBucket didnt notice u were here lol

**Pull request closed without merging**
