### PR TITLE
Create you.json

### PR DESCRIPTION
**Pull request by thaihung48**

### CODE REVIEW

**Comment by trollm8** [comment]
Hello there, Please give me a reason why NS is needed for your subdomain

**Comment by thaihwng** [comment]
Because I want to enable custom domain configurations, specifically for email management

**Comment by thaihung48** [comment]
> Hello there, Please give me a reason why NS is needed for your subdomain

Because I want to enable custom domain configurations, specifically for email management.!

**Comment by CuteDog5695** [comment]
By custom domain configuration, ya mean editing records easier?

**Comment by thaihung48** [comment]
> By custom domain configuration, ya mean editing records easier?

Yes, that's right

**Pull request merged**
